### ISSUE TITLE
Remote File Manager - usage

### ISSUE THREAD

**Issue by ihrapsa** [melianmiko/SmartBand7-Apps#14]
Hey,  the app [webpage](https://melianmiko.ru/en/sb7/toolbox/) states that  it can `manage files in the bracelet's memory from your phone or computer`. I'd like to know what are the requirements to achieve that. I managed to install the app using the zepp app (with QR code) but things stop there. 
Thank you!

**Comment by melianmiko** [comment]
Hi.

1. Launch toolbox;
2. Select "Settings" at bottom;
3. Select "Remote manager" and follow instructions on screen.

![2023-09-06_03-56](https://github.com/melianmiko/ZeppOS-Toolbox/assets/67851274/ea9bef93-280d-4b0a-9249-d76bb5f90b5e) ![2023-09-06_03-56_2](https://github.com/melianmiko/ZeppOS-Toolbox/assets/67851274/7904e016-1d3b-429f-b756-1bbb214b6584) ![2023-09-06_03-56_1](https://github.com/melianmiko/ZeppOS-Toolbox/assets/67851274/1474aa5e-e6ab-45b0-b74f-946020c9d602)

**Comment by ihrapsa** [comment]
Really appreciate the fast reply. For some reason I don’t get the last screen with the link, only a _`Connecting...`_ message that hangs there. 
I'm using a global _`Xiaomi Smart Band 7 with NFC`_. It might be related to the fact that none of the modded versions of Zepp app (7.7.0, 7.75 or 7.9.1) are able to add the band as Amazfit Band 7? The pairing seems to be successful at first with confirmation on band, BUT the band is never added in the app's Profile tab (under My Devices). 

The only way I managed to add it was with a [ 7.0.1 ](https://disk.yandex.ru/d/kwOfa0LPm2N3CQ)version found on [this blog](https://habr.com/en/articles/699368/). However, the name is still _Xiaomi Smart Band 7 NFC_ in My Devices list, there is _no App store_ and the _Mini programs_ that get installed on the band with the QR code disappear from Developer menu so can't see logs or anything.

This is the only QR URL without mac address that worked for me: `https://api-watch.huami.com/forwarding/watchUS?macAddress=XXXXXXXXXXX&pnpNumber=117&pnpVersion=256`. Only `256` and `259` _pnpVersions_ managed to add the band.

![image](https://github.com/melianmiko/ZeppOS-Toolbox/assets/40600040/cb316c76-b41d-4c32-98dd-6d6395e23560)


Any idea how I could go about this?

**Comment by melianmiko** [comment]
Could you please give `pnpNumber` and `pnpVersion` from QR-code that your Mi Band show after factory reset?

**Comment by ihrapsa** [comment]
> Could you please give `pnpNumber` and `pnpVersion` from QR-code that your Mi Band show after factory reset?

Scanning the factory reset QR gives me `pnpNumber `= `103` and `pnpVersion` =`257`

**Comment by melianmiko** [comment]
Fine, I'll check a bit later how my modification of Zepp handles this revision.

**Comment by ihrapsa** [comment]
> Fine, I'll check a bit later how my modification of Zepp handles this revision.

Thank you!!!
