### ISSUE TITLE
Uncnown bug with PDF417 in Wallet mini app

### ISSUE THREAD

**Issue by lavafrai** [melianmiko/SmartBand7-Apps#5]
В приложении "кошелек" при попытке создания карты, использующей PDF471, с данными длинной 16 символов, приложение останавливается с ошибкой.
Не могу прикрепить логи или какую либо подробную информацию об ошибке, так как не могу добыть их с моего браслета.
Не могли бы вы, зная свой проект и как его можно отлаживать посмотреть, в чем может заключаться проблема? Ошибка воспроизводится при каждой попытке создать карту PDF417 с большим количеством символов (В моем случае 16).

Если интересно, карта - новая карта x5 club (Пятерочка, перекресток) если знаете в чем может быть проблема, скажите, может попробую исправить самостоятельно.

**Comment by melianmiko** [comment]
Проблема была в библиотеке, которую я выбрал для их генерации. Вроде починил, пришлось для тестов обзавестись картой пятёрочки правда =)
